# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Linkify' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Linkify
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'LinkifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Linkify-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Linkify-tvOS

  target 'Linkify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
